insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('kdonnel0@delicious.com', 'agosnoll0', 'biek10fSqb', 'Kyle', 'Donnel', 'MALE', '2019-12-12', 'United States', 'Indianapolis', '8 Holy Cross Lane', 'kdonnel0@stumbleupon.com', '317-706-8716', 'jugem.jp', 'creativecommons.org', 'businessweek.com', 'archive.org', '2020-05-20', '2020-04-13', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('nlefeaver1@eventbrite.com', 'qmidford1', 'r2cIj4kGS', 'Noach', 'Le feaver', 'MALE', '2020-07-30', 'Russia', 'Zelenogorsk', '59414 Knutson Road', 'nlefeaver1@businessinsider.com', '623-703-7182', 'ftc.gov', 'cyberchimps.com', 'spiegel.de', 'archive.org', '2020-06-25', '2020-05-29', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('jphil2@pagesperso-orange.fr', 'ksictornes2', 'sJoSWE', 'Jae', 'Phil', 'MALE', '2019-12-05', 'Slovenia', 'Gornji Petrovci', '017 Pond Court', 'jphil2@ning.com', '393-826-6562', 'google.ru', 't-online.de', 'alexa.com', 'wordpress.org', '2020-03-03', '2020-07-27', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('emcnamara3@ustream.tv', 'gwahncke3', '0aK7lzEQ', 'Eduardo', 'McNamara', 'MALE', '2020-03-24', 'Philippines', 'Pura', '7916 Donald Way', 'emcnamara3@weebly.com', '110-724-4105', 'people.com.cn', 'paginegialle.it', 'sogou.com', 'yahoo.co.jp', '2020-09-03', '2020-01-29', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('dsurmeyer4@hibu.com', 'gibeson4', 'V1Rw13bAh', 'Dolly', 'Surmeyer', 'FEMALE', '2020-01-07', 'China', 'Qingkou', '9 Sunnyside Street', 'dsurmeyer4@upenn.edu', '131-523-1295', 'constantcontact.com', 'jigsy.com', 'reddit.com', 'google.es', '2020-08-21', '2020-02-08', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('lpreon5@guardian.co.uk', 'cmcnirlin5', 'JfQYRKT', 'Loni', 'Preon', 'FEMALE', '2020-06-21', 'Dominican Republic', 'El Cacao', '64 Sherman Circle', 'lpreon5@merriam-webster.com', '997-257-6135', 'weebly.com', 'webs.com', 'tumblr.com', 'surveymonkey.com', '2020-08-26', '2019-12-13', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('mdurtnell6@eepurl.com', 'ctoretta6', 'bTirKauu1T', 'Mortimer', 'Durtnell', 'MALE', '2020-05-03', 'Israel', 'Qiryat Yam', '099 Marcy Street', 'mdurtnell6@uol.com.br', '598-786-1293', 'china.com.cn', 'prnewswire.com', 'squidoo.com', 'nbcnews.com', '2020-08-14', '2019-12-20', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('svivians7@patch.com', 'evanichkin7', 'Q88o09ur6Q', 'Stephi', 'Vivians', 'FEMALE', '2020-07-04', 'Indonesia', 'Tembol', '73029 Artisan Avenue', 'svivians7@devhub.com', '475-570-5060', 'baidu.com', 'blinklist.com', 'cyberchimps.com', 'google.co.jp', '2020-01-07', '2020-11-14', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('kluberto8@pen.io', 'mkite8', 'WTUjq0zxpbf', 'Kerrie', 'Luberto', 'FEMALE', '2020-10-25', 'Rwanda', 'Nzega', '9 Anderson Crossing', 'kluberto8@redcross.org', '268-819-6252', 'imgur.com', 'webeden.co.uk', 'a8.net', 'symantec.com', '2020-04-03', '2020-07-29', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('wkendred9@usa.gov', 'pmoyne9', 'flM2VljeS', 'Winthrop', 'Kendred', 'MALE', '2019-12-07', 'Spain', 'Cartagena', '9 Grasskamp Lane', 'wkendred9@army.mil', '918-244-7183', 'chron.com', 'xrea.com', 'webnode.com', 'rakuten.co.jp', '2020-10-02', '2020-06-28', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('tbrugha@bluehost.com', 'jkubiaka', 'XpjqTjiRmv', 'Tess', 'Brugh', 'FEMALE', '2020-08-05', 'Sweden', 'Helsingborg', '9 Anthes Point', 'tbrugha@hud.gov', '974-751-4222', 'admin.ch', 'multiply.com', 'ox.ac.uk', 'blog.com', '2020-04-23', '2020-07-15', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('wmullengerb@jimdo.com', 'tthomingab', '3eo6ghQ', 'Winni', 'Mullenger', 'FEMALE', '2020-06-14', 'China', 'Jiaqiao', '71 Farragut Parkway', 'wmullengerb@businessweek.com', '192-851-8873', 'amazon.co.jp', 'ameblo.jp', 'wiley.com', 'addthis.com', '2020-04-12', '2020-02-21', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('rlamarc@smh.com.au', 'dobradanec', 'hMcP33Muf1', 'Ramsey', 'Lamar', 'MALE', '2020-04-17', 'China', 'Wujian', '2 Jenifer Center', 'rlamarc@bloglovin.com', '673-752-6235', 'rediff.com', 'a8.net', 'barnesandnoble.com', 'usa.gov', '2020-07-05', '2020-01-27', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('slovelandd@altervista.org', 'arapportd', 'jjSkvvUx', 'Salvatore', 'Loveland', 'MALE', '2020-08-26', 'Finland', 'Outokumpu', '8855 Chive Junction', 'slovelandd@over-blog.com', '742-877-1641', 'ovh.net', 'intel.com', 'twitpic.com', 'telegraph.co.uk', '2020-08-11', '2020-08-08', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('bdonisie@netvibes.com', 'eplayhille', '9hDiPDxfx', 'Batsheva', 'D''Onisi', 'FEMALE', '2020-03-12', 'China', 'Luoqiao', '86 Warrior Point', 'bdonisie@addthis.com', '445-116-6602', 'woothemes.com', 'bloglovin.com', 'china.com.cn', 'microsoft.com', '2020-07-11', '2020-06-29', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('jfowleyf@naver.com', 'rbainbridgef', 'uAnKhQ', 'Jeramie', 'Fowley', 'MALE', '2020-05-06', 'Norway', 'Oslo', '9 Orin Court', 'jfowleyf@gov.uk', '757-713-6418', 'edublogs.org', 'ed.gov', 'sohu.com', 'nih.gov', '2020-07-14', '2020-04-20', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('gpietaschg@oracle.com', 'cbuchang', 'hNXMci6x', 'Gustaf', 'Pietasch', 'MALE', '2019-11-30', 'China', 'Qiaotou', '152 Pleasure Pass', 'gpietaschg@wix.com', '480-772-9633', 'icq.com', 'miitbeian.gov.cn', 'squarespace.com', 'nasa.gov', '2020-02-27', '2020-03-24', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('ddunnanh@mit.edu', 'lrubinovicih', 'FVuZhTLA2JC3', 'Dave', 'Dunnan', 'MALE', '2020-01-30', 'Japan', 'Shirone', '20399 Bluestem Alley', 'ddunnanh@utexas.edu', '635-605-2506', 'seattletimes.com', 'gravatar.com', 'latimes.com', '51.la', '2019-12-23', '2020-05-24', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('gmacteggarti@taobao.com', 'speretti', 'y8jBtnVTUK', 'Glenden', 'MacTeggart', 'MALE', '2020-02-10', 'China', 'Dongqinggou', '10 Gina Park', 'gmacteggarti@vk.com', '664-753-8661', 'yale.edu', 'squidoo.com', 'plala.or.jp', 'mit.edu', '2020-06-09', '2020-10-19', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('bugolettij@hp.com', 'amittenj', '4zEObz703Ze', 'Betsey', 'Ugoletti', 'FEMALE', '2020-04-19', 'Brazil', 'Pirapozinho', '7954 Michigan Alley', 'bugolettij@vistaprint.com', '589-851-5632', 'deviantart.com', 'ustream.tv', 'businessinsider.com', 'addtoany.com', '2020-02-13', '2020-03-08', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('mrandlesk@slate.com', 'awoolgerk', 'HwurDtSnpQ', 'Morganne', 'Randles', 'FEMALE', '2020-02-11', 'Russia', 'Otradnyy', '23038 Hintze Avenue', 'mrandlesk@thetimes.co.uk', '779-378-6066', 'seesaa.net', 'eepurl.com', 'nasa.gov', 'cdc.gov', '2020-07-09', '2020-05-12', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('gbickertonl@bloomberg.com', 'eclarkl', 'TRwot6', 'Gamaliel', 'Bickerton', 'MALE', '2020-10-20', 'Paraguay', 'Bella Vista', '2 Sutteridge Point', 'gbickertonl@sciencedirect.com', '386-345-5508', 'patch.com', 'ed.gov', 'economist.com', 'tinyurl.com', '2020-03-20', '2020-03-09', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('estrutzm@squidoo.com', 'emaypesm', 'oEpOnKYVm7', 'Ernst', 'Strutz', 'MALE', '2020-08-09', 'Sierra Leone', 'Motema', '6 Dovetail Park', 'estrutzm@about.me', '697-587-9254', 'pcworld.com', 'i2i.jp', 'sitemeter.com', 'cafepress.com', '2020-07-26', '2020-10-24', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('stannn@nytimes.com', 'kradkin', 'qwoDzM0', 'Stevena', 'Tann', 'FEMALE', '2020-01-18', 'China', 'Xinjian', '779 Del Sol Road', 'stannn@mtv.com', '449-839-3513', 'shinystat.com', 'people.com.cn', 'admin.ch', 'instagram.com', '2020-09-15', '2020-11-24', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('vgregsono@vinaora.com', 'jgierathso', 'RTmZKKJ5OQDP', 'Victor', 'Gregson', 'MALE', '2020-05-31', 'Indonesia', 'Pulosari', '3 Algoma Trail', 'vgregsono@infoseek.co.jp', '760-769-4258', 'icio.us', 'apache.org', 'arstechnica.com', 'woothemes.com', '2020-03-25', '2020-07-09', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('smugridgep@soup.io', 'lferrerp', 'wpCSx8qhvEF', 'Saunder', 'Mugridge', 'MALE', '2020-09-22', 'Russia', 'Nikolina Gora', '4 Lawn Circle', 'smugridgep@liveinternet.ru', '517-174-0380', 'kickstarter.com', 'e-recht24.de', 'people.com.cn', 'bizjournals.com', '2020-11-02', '2020-11-07', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('xgormallyq@csmonitor.com', 'sriddeoughq', '4evrCSKH8sm', 'Xavier', 'Gormally', 'MALE', '2020-08-10', 'Ireland', 'Prosperous', '42 Petterle Alley', 'xgormallyq@eepurl.com', '905-587-7637', 'etsy.com', 'fda.gov', 'amazon.co.jp', 'prnewswire.com', '2019-12-21', '2019-12-23', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('tkeaner@huffingtonpost.com', 'rlibbyr', 'IGfwR8PzlU', 'Torrence', 'Keane', 'MALE', '2020-02-15', 'Greece', 'Ambelón', '29 Corry Terrace', 'tkeaner@ibm.com', '840-719-1220', 'addtoany.com', 'dmoz.org', 'hp.com', 'reddit.com', '2020-04-14', '2020-04-22', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('mmcglues@goo.gl', 'mstannings', '54GB4gDIXf', 'Malchy', 'McGlue', 'MALE', '2019-12-08', 'Djibouti', 'Ḏânan', '3 Crowley Place', 'mmcglues@tmall.com', '308-383-1369', 'vinaora.com', 'tamu.edu', 'wix.com', 'last.fm', '2020-06-04', '2020-03-28', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('mbovairdt@baidu.com', 'cbrokenbrowt', 'kadATyegdt', 'Maison', 'Bovaird', 'MALE', '2020-05-10', 'Colombia', 'Chaguaní', '0034 Merchant Junction', 'mbovairdt@wp.com', '453-884-3247', 'woothemes.com', 'cloudflare.com', 'plala.or.jp', 'sbwire.com', '2020-08-15', '2020-10-15', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('sbeartu@flavors.me', 'dbrettoru', 'kliSV9EEgc', 'Scarlet', 'Beart', 'FEMALE', '2020-05-30', 'Indonesia', 'Cirateun', '849 Summerview Way', 'sbeartu@wp.com', '208-781-6672', 'ehow.com', 'ft.com', 'amazon.co.uk', 'senate.gov', '2020-08-06', '2019-12-09', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('ddeblev@statcounter.com', 'doroanv', 'znMUnu3h', 'Darius', 'Deble', 'MALE', '2020-08-11', 'Cameroon', 'Penja', '0 Main Lane', 'ddeblev@soup.io', '457-526-6685', 'si.edu', 'theglobeandmail.com', 'irs.gov', 'java.com', '2020-08-31', '2020-04-01', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('mwinmanw@addtoany.com', 'efrankemaw', 'uQwO1HxzkG22', 'Merv', 'Winman', 'MALE', '2019-12-13', 'Taiwan', 'Nangan', '40 Fordem Junction', 'mwinmanw@hhs.gov', '999-601-8916', 'cocolog-nifty.com', 'google.it', 'tuttocitta.it', 'ucoz.ru', '2020-03-25', '2020-07-22', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('rcristofaninix@posterous.com', 'nmarquezx', 'r0lwLI9', 'Reuben', 'Cristofanini', 'MALE', '2020-10-17', 'China', 'Hepu', '0 Lakeland Hill', 'rcristofaninix@fda.gov', '179-853-5748', 'vimeo.com', 'blinklist.com', 'wp.com', 'google.pl', '2020-10-11', '2020-02-18', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('tlettericky@about.me', 'tcuttlesy', 'YKGVyop8', 'Tansy', 'Letterick', 'FEMALE', '2020-08-24', 'Indonesia', 'Gunung Timur', '013 Eggendart Hill', 'tlettericky@delicious.com', '944-680-7099', 'hud.gov', 'earthlink.net', 'dropbox.com', 'hud.gov', '2020-01-03', '2020-10-21', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('mblurtonz@aol.com', 'ljeffelsz', 'yvrbI7v8', 'Maurizio', 'Blurton', 'MALE', '2020-03-31', 'France', 'Montfort-sur-Meu', '6 Miller Junction', 'mblurtonz@cornell.edu', '405-921-6693', 'fc2.com', 'bing.com', 'people.com.cn', 'deliciousdays.com', '2020-03-18', '2020-08-11', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('adann10@cargocollective.com', 'dthroughton10', 'lYVIXhB', 'Anabelle', 'Dann', 'FEMALE', '2020-08-02', 'China', 'Chaoyang', '7390 Manitowish Point', 'adann10@so-net.ne.jp', '836-466-1213', 'marriott.com', 'jalbum.net', 'ibm.com', 'facebook.com', '2020-09-17', '2020-06-27', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('cdumbrall11@cnn.com', 'dpiggott11', 'ihh9rSp4', 'Con', 'Dumbrall', 'MALE', '2020-07-21', 'Spain', 'Teruel', '73197 Mandrake Avenue', 'cdumbrall11@cbsnews.com', '208-916-8951', 'sakura.ne.jp', 'live.com', 'oakley.com', 'unc.edu', '2020-08-15', '2020-09-05', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('mwyson12@google.cn', 'lbantham12', 'AmLatO0pfJbQ', 'Marv', 'Wyson', 'MALE', '2020-11-04', 'Czech Republic', 'Předměřice nad Labem', '83474 Swallow Lane', 'mwyson12@t-online.de', '522-913-1583', 'accuweather.com', 'pbs.org', 'yale.edu', '1688.com', '2020-08-08', '2020-04-05', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('sitzchaky13@dropbox.com', 'mtyt13', 'kX1Ag2A', 'Sabine', 'Itzchaky', 'FEMALE', '2020-04-13', 'Kazakhstan', 'Terenozek', '78352 Manitowish Pass', 'sitzchaky13@theguardian.com', '359-242-8169', 'livejournal.com', 'irs.gov', 'domainmarket.com', 'tinypic.com', '2020-01-26', '2020-10-02', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('clandreth14@ycombinator.com', 'phospital14', 'ZjGXARXMB8', 'Cletus', 'Landreth', 'MALE', '2020-08-26', 'Philippines', 'Guinsadan', '8296 School Center', 'clandreth14@people.com.cn', '552-797-5015', 'desdev.cn', 'google.co.uk', 'indiegogo.com', 'rakuten.co.jp', '2020-11-13', '2020-02-07', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('fshellcross15@hostgator.com', 'ngommowe15', 'pujzwnBP', 'Findley', 'Shellcross', 'MALE', '2020-06-11', 'France', 'Challans', '3965 South Point', 'fshellcross15@theguardian.com', '675-351-5765', 'wordpress.org', 'skyrock.com', 'wikimedia.org', 'mit.edu', '2020-02-05', '2020-02-16', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('dmitcham16@networkadvertising.org', 'aborer16', 'PbsehpPT0V', 'Dayna', 'Mitcham', 'FEMALE', '2020-02-01', 'China', 'Shitouhe', '0 Elgar Crossing', 'dmitcham16@si.edu', '160-846-5778', 'pagesperso-orange.fr', 'theglobeandmail.com', 'amazon.com', 'ftc.gov', '2020-01-11', '2020-02-20', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('osteaning17@mapy.cz', 'ehuckin17', 'pmNtmysKNFNs', 'Oates', 'Steaning', 'MALE', '2020-02-05', 'Belarus', 'Horad Krychaw', '5 Chive Point', 'osteaning17@paginegialle.it', '261-284-4702', 'bizjournals.com', 'cloudflare.com', 'oakley.com', 'blog.com', '2020-05-21', '2020-08-03', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('echipp18@canalblog.com', 'bmaccartair18', 'l9F0kpLi6Y2', 'Ezequiel', 'Chipp', 'MALE', '2020-10-01', 'United States', 'Scottsdale', '563 Monterey Parkway', 'echipp18@godaddy.com', '480-463-9182', 'discuz.net', 'dagondesign.com', 'tamu.edu', 'diigo.com', '2020-11-09', '2020-01-18', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('pmcniven19@studiopress.com', 'egault19', '0Kp2V4Jgh', 'Persis', 'McNiven', 'FEMALE', '2019-12-03', 'Russia', 'Tigil’', '10824 Vermont Drive', 'pmcniven19@cdc.gov', '343-392-4350', 'seesaa.net', 'ameblo.jp', 'latimes.com', 'illinois.edu', '2020-08-12', '2020-10-13', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('kcowsby1a@webs.com', 'dbelliss1a', '6d8lNY1u4mFL', 'Karly', 'Cowsby', 'FEMALE', '2020-03-19', 'Serbia', 'Svilajnac', '85639 South Avenue', 'kcowsby1a@noaa.gov', '265-572-6591', 'gmpg.org', 'usa.gov', '4shared.com', 'ustream.tv', '2019-12-31', '2020-08-02', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('coverton1b@army.mil', 'rvinecombe1b', 'akIftDZqi', 'Carly', 'Overton', 'FEMALE', '2019-12-25', 'Saudi Arabia', 'Mizhirah', '31 Gerald Road', 'coverton1b@purevolume.com', '958-127-7741', 'prnewswire.com', 'shop-pro.jp', 'stanford.edu', 'howstuffworks.com', '2020-10-21', '2020-05-20', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('abrabon1c@parallels.com', 'lkenealy1c', 'tnH5Dd', 'Aeriell', 'Brabon', 'FEMALE', '2019-12-15', 'Nicaragua', 'Masaya', '379 Toban Hill', 'abrabon1c@booking.com', '675-970-9248', 'usnews.com', 'google.de', 'state.tx.us', 'forbes.com', '2020-08-25', '2020-09-02', false);
insert into users (email, login, password, first_name, last_name, gender, birthday, country, city, address, contact_email, contact_number, contact_facebook, contact_vk, contact_telegram, contact_instagram, registration_time, update_time, delete) values ('dlempel1d@joomla.org', 'ehiorn1d', 'DQp66FU3t95J', 'Devin', 'Lempel', 'MALE', '2020-11-05', 'China', 'Shimen', '12015 Heffernan Hill', 'dlempel1d@hugedomains.com', '981-738-8325', 'bravesites.com', 'blogspot.com', 'paypal.com', 'ftc.gov', '2020-08-07', '2020-09-22', false);


insert into dialogs (delete, created) values (false, '2020-09-14');
insert into dialogs (delete, created) values (false, '2020-05-29');
insert into dialogs (delete, created) values (false, '2020-11-27');
insert into dialogs (delete, created) values (false, '2020-07-06');
insert into dialogs (delete, created) values (false, '2020-05-15');
insert into dialogs (delete, created) values (false, '2020-11-24');
insert into dialogs (delete, created) values (false, '2020-05-11');
insert into dialogs (delete, created) values (false, '2020-03-29');
insert into dialogs (delete, created) values (false, '2020-04-13');
insert into dialogs (delete, created) values (false, '2020-05-09');
insert into dialogs (delete, created) values (false, '2020-10-18');
insert into dialogs (delete, created) values (false, '2020-08-02');
insert into dialogs (delete, created) values (false, '2020-03-19');
insert into dialogs (delete, created) values (false, '2019-12-10');
insert into dialogs (delete, created) values (false, '2020-08-12');
insert into dialogs (delete, created) values (false, '2020-05-30');
insert into dialogs (delete, created) values (false, '2020-09-17');
insert into dialogs (delete, created) values (false, '2020-06-20');
insert into dialogs (delete, created) values (false, '2020-04-17');
insert into dialogs (delete, created) values (false, '2020-09-24');
insert into dialogs (delete, created) values (false, '2020-07-16');
insert into dialogs (delete, created) values (false, '2019-11-29');
insert into dialogs (delete, created) values (false, '2020-08-09');
insert into dialogs (delete, created) values (false, '2020-05-21');
insert into dialogs (delete, created) values (false, '2020-05-29');
insert into dialogs (delete, created) values (false, '2020-09-17');
insert into dialogs (delete, created) values (false, '2020-02-09');
insert into dialogs (delete, created) values (false, '2020-05-05');
insert into dialogs (delete, created) values (false, '2020-08-30');
insert into dialogs (delete, created) values (false, '2020-05-11');
insert into dialogs (delete, created) values (false, '2020-08-21');
insert into dialogs (delete, created) values (false, '2020-01-08');
insert into dialogs (delete, created) values (false, '2020-04-22');
insert into dialogs (delete, created) values (false, '2020-07-21');
insert into dialogs (delete, created) values (false, '2020-02-16');
insert into dialogs (delete, created) values (false, '2020-05-08');
insert into dialogs (delete, created) values (false, '2020-10-28');
insert into dialogs (delete, created) values (false, '2020-01-09');
insert into dialogs (delete, created) values (false, '2020-02-11');
insert into dialogs (delete, created) values (false, '2020-07-26');
insert into dialogs (delete, created) values (false, '2020-07-19');
insert into dialogs (delete, created) values (false, '2020-10-17');
insert into dialogs (delete, created) values (false, '2019-12-23');
insert into dialogs (delete, created) values (false, '2020-09-04');
insert into dialogs (delete, created) values (false, '2020-06-30');
insert into dialogs (delete, created) values (false, '2020-08-30');
insert into dialogs (delete, created) values (false, '2020-01-23');
insert into dialogs (delete, created) values (false, '2020-05-27');
insert into dialogs (delete, created) values (false, '2020-08-07');
insert into dialogs (delete, created) values (false, '2020-04-20');



insert into user_dialogs values (1,2);
insert into user_dialogs values (1,1);
insert into user_dialogs values (2,3);
insert into user_dialogs values (2,2);
insert into user_dialogs values (3,4);
insert into user_dialogs values (3,2);
insert into user_dialogs values (4,5);
insert into user_dialogs values (4,6);


insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,1,'Hello buddy! From 1 to 2. Dialog 1',2,1);
insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,2,'Hello you to buddy! From 2 to 1. Dialog 1',1,1);
insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,2,'Hello you to buddy! From 2 to 3. Dialog 2',3,2);
insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,3,'Hello you to buddy! From 3 to 2. dialog 2',2,2);
insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,4,'Hello you to buddy! From 4 to 2. dialog 3',2,3);
insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,2,'Hello you to buddy! From 2 to 4. dialog 3',4,3);
insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,5,'Hello you to buddy! From 2 to 4. dialog 4',6,4);
insert into messages (created, delete, edited, from_who, text, to_who, dialog_id) values ('2020-10-11',false,false,6,'Hello you to buddy! From 2 to 4. dialog 4',5,4);


insert into user_friends values (1,2);
insert into user_friends values (1,3);
insert into user_friends values (1,4);
insert into user_friends values (1,5);
insert into user_friends values (1,6);
insert into user_friends values (1,7);
insert into user_friends values (1,8);
insert into user_friends values (1,9);
insert into user_friends values (2,3);
insert into user_friends values (2,4);
insert into user_friends values (2,5);
insert into user_friends values (2,6);
insert into user_friends values (2,7);
insert into user_friends values (2,8);
insert into user_friends values (2,9);
insert into user_friends values (3,2);
insert into user_friends values (3,3);
insert into user_friends values (3,4);
insert into user_friends values (3,5);
insert into user_friends values (3,6);
insert into user_friends values (3,7);
insert into user_friends values (3,8);
insert into user_friends values (3,9);
insert into user_friends values (3,3);
insert into user_friends values (3,4);
insert into user_friends values (3,5);
insert into user_friends values (3,6);
insert into user_friends values (3,7);
insert into user_friends values (3,8);
insert into user_friends values (3,9);

insert into user_subscribers values (1,30);
insert into user_subscribers values (1,31);
insert into user_subscribers values (1,32);
insert into user_subscribers values (1,33);
insert into user_subscribers values (1,34);
insert into user_subscribers values (1,35);
insert into user_subscribers values (1,36);
insert into user_subscribers values (1,37);
insert into user_subscribers values (1,38);
insert into user_subscribers values (1,39);
insert into user_subscribers values (1,40);


insert into text (created, delete, edited, text, user_id) values ('2020-04-13 00:00:00.000000',false,false,'Hello its 1st text of user1',1);
insert into text (created, delete, edited, text, user_id) values ('2020-04-13 01:00:00.000000',false,false,'Hello its 2st text of user1',1);
insert into text (created, delete, edited, text, user_id) values ('2020-04-13 02:00:00.000000',false,false,'Hello its 3st text of user1',1);
insert into text (created, delete, edited, text, user_id) values ('2020-04-13 03:00:00.000000',false,false,'Hello its 4st text of user1',1);
insert into text (created, delete, edited, text, user_id) values ('2020-04-13 04:00:00.000000',false,false,'Hello its 5st text of user1',1);
insert into text (created, delete, edited, text, user_id) values ('2020-04-13 05:00:00.000000',false,false,'Hello its 6st text of user1',1);
insert into text (created, delete, edited, text, user_id) values ('2020-04-13 06:00:00.000000',false,false,'Hello its 7st text of user1',1);
insert into text (created, delete, edited, text, user_id) values ('2020-04-13 07:00:00.000000',false,false,'Hello its 8st text of user1',1);


insert into text_comments (comment, created, deleted, edited, text_id, user_id) values ('Hi man, its comment for user text','2020-05-13 00:00:00.000000',false,false,1,1);
insert into text_comments (comment, created, deleted, edited, text_id, user_id) values ('Hi man, its comment for user text','2020-05-13 02:00:00.000000',false,false,2,1);
insert into text_comments (comment, created, deleted, edited, text_id, user_id) values ('Hi man, its comment for user text','2020-05-13 05:00:00.000000',false,false,3,1);
insert into text_comments (comment, created, deleted, edited, text_id, user_id) values ('Hi man, its comment for user text','2020-05-13 08:00:00.000000',false,false,4,1);
insert into text_comments (comment, created, deleted, edited, text_id, user_id) values ('Hi man, its comment for user text','2020-05-13 09:00:00.000000',false,false,5,1);